export const audioMap = {
  "Welcome to the Great Sky Race!": "/assets/audio/audio_welcome_to_the_great_sky_race__0.mp3",
  "Today, we are going to learn how to compare and order large numbers.": "/assets/audio/audio_today__we_are_going_to_learn_how_to_compare_and_or_1.mp3",
  "Who gets to launch first? Let us find out!": "/assets/audio/audio_who_gets_to_launch_first__let_us_find_out__2.mp3",
  "Are you ready to explore space and solve some fun challenges? Let us get started on our learning journey!": "/assets/audio/audio_are_you_ready_to_explore_space_and_solve_some_fun__3.mp3",
  "Which rocket has more fuel?": "/assets/audio/audio_which_rocket_has_more_fuel__4.mp3",
  "Mission Control says only the bigger number gets to launch!": "/assets/audio/audio_mission_control_says_only_the_bigger_number_gets_t_5.mp3",
  "Sarah's fuel reads 3,847. John's reads 4,219. Mission Control announces only the pilot with the bigger number gets to launch!": "/assets/audio/audio_sarah_s_fuel_reads_3_847__john_s_reads_4_219__miss_6.mp3",
  "Which is bigger: 3,847 or 4,219?": "/assets/audio/audio_which_is_bigger__3_847_or_4_219__7.mp3",
  "We have to compare the numbers!": "/assets/audio/audio_we_have_to_compare_the_numbers__8.mp3",
  "Mike the fuel engineer says \"Bigger number equals more fuel equals longer flight!\"": "/assets/audio/audio_mike_the_fuel_engineer_says__bigger_number_equals__9.mp3",
  "But how do you know which is bigger when the numbers are so huge?": "/assets/audio/audio_but_how_do_you_know_which_is_bigger_when_the_numbe_10.mp3",
  "Hmm... maybe we look at the digits?": "/assets/audio/audio_hmm____maybe_we_look_at_the_digits__11.mp3",
  "Priya pulls up the Place Value Ladder! She compares the THOUSANDS digit first.": "/assets/audio/audio_priya_pulls_up_the_place_value_ladder__she_compare_12.mp3",
  "4 thousands is more than 3 thousands. John wins!": "/assets/audio/audio_4_thousands_is_more_than_3_thousands__john_wins__13.mp3",
  "But wait! Lena, Omar, and Aiko also want to race! Now we have to order all their fuel readings from least to greatest.": "/assets/audio/audio_but_wait__lena__omar__and_aiko_also_want_to_race___14.mp3",
  "We can use the ladder again!": "/assets/audio/audio_we_can_use_the_ladder_again__15.mp3",
  "Using the Place Value Ladder, Mission Control orders all the rockets.": "/assets/audio/audio_using_the_place_value_ladder__mission_control_orde_16.mp3",
  "The race begins and the rockets blast off into space!": "/assets/audio/audio_the_race_begins_and_the_rockets_blast_off_into_spa_17.mp3",
  "Adjust the dials to change the fuel numbers. Watch the ladder!": "/assets/audio/audio_adjust_the_dials_to_change_the_fuel_numbers__watch_18.mp3",
  "Drag the rocket to land close to the target!": "/assets/audio/audio_drag_the_rocket_to_land_close_to_the_target__19.mp3",
  "Drag the cards to order them!": "/assets/audio/audio_drag_the_cards_to_order_them__20.mp3",
  "Welcome to Level 1: Cadet!": "/assets/audio/audio_welcome_to_level_1__cadet__21.mp3",
  "Welcome to Level 2: Navigator!": "/assets/audio/audio_welcome_to_level_2__navigator__22.mp3",
  "Welcome to Level 3: Commander!": "/assets/audio/audio_welcome_to_level_3__commander__23.mp3",
  "Level 1: Cadet Complete!": "/assets/audio/audio_level_1__cadet_complete__24.mp3",
  "Level 2: Navigator Complete!": "/assets/audio/audio_level_2__navigator_complete__25.mp3",
  "Level 3: Commander Complete!": "/assets/audio/audio_level_3__commander_complete__26.mp3",
  "What did you learn about comparing numbers?": "/assets/audio/audio_what_did_you_learn_about_comparing_numbers__27.mp3",
  "How confident do you feel about comparing numbers?": "/assets/audio/audio_how_confident_do_you_feel_about_comparing_numbers__28.mp3"
};
